IntAdd=0
IntSub=1
IntPSub=2
PrintI=3
IntEq=4
IntType=5
PrintB=6
BoolType=7
ExitFunction=8
IntasAdd=9
IntaAdd=10
IntAAdd=11
IntASAdd=12
IntAsAdd=13
IntAss=14
IntAsss=15
IntAsssi=16
IntAsssig=17
IntAsssign=18
IntAssign=19
IntPA=20
IntPAd=21
IntPAdd=22
I=23
In=24
Int=25
IntA=26
IntAs=27
IntAsS=28
IntAsSu=29
IntAsSub=30
IntM=31
IntMu=32
IntMul=33
IntAsMul=34
IntAsDiv=35
IntDiv=36
i=37
int=38
intM=39
intMo=40
intMod=41
ntMod=42
IntMod=43
IntAsM=44
IntAsMo=45
IntAsMod=46
B=47
Bo=48
Boo=49
Bool=50
BoolA=51
BoolAn=52
BoolAnd=53
