IntN=0
IntNE=1
IntAdd=2
IntAsAdd=3
IntSub=4
IntPSub=5
IntAsSub=6
PrintI=7
IntPAdd=8
IntMul=9
IntAsMul=10
IntDiv=11
IntAsDiv=12
IntMod=13
IntAsMod=14
IntEq=15
IntGT=16
IntLT=17
IntGE=18
IntLE=19
IntTyintpe=20
IntAssign=21
PrintB=22
BoolAnd=23
BoolAsAnd=24
BoolOr=25
BoolAsOr=26
BoolNot=27
BoolType=28
BoolAssign=29
ExitFunction=30
BoolE=31
BoolEq=32
BoolNE=33
IntType=34
IsNullFunction=35
P=36
Pr=37
Pri=38
Prin=39
Print=40
PrintNL=41
IntAddition=42
IntAddition=42
IntAsssignAddition=43
IntAsssignAddition=43
IntPrefixAddition=44
IntPrefixAddition=44
IntSubtract=45
IntAssignSubtract=46
IntAssignSubtract=46
IntPrefixSubtract=47
IntPrefixSubtract=47
IntMultiply=48
IntMultiply=48
IntAssignMultiply=49
IntDivide=50
IntDivide=50
IntAssignDivide=51
IntModulo=52
IntAssignModulo=53
IntEqual=54
IntEqual=54
IntNotEqual=55
IntNotEqual=55
IntGreaterThan=56
IntGreaterThan=56
IntLessThan=57
IntGreaterThanEqual=58
IntGreaterThanEqual=58
IntLessThanEqual=59
PrintInt=60
PrintInt=60
PrintBool=61
PrintBool=61
BoolEqual=62
BoolEqual=62
BoolNotEqual=63
BoolAssignAnd=64
BoolAssignAnd=64
BoolAssignOr=65
BoolAssignOr=65
IntAssignAddition=66
