WindowsExit=0
PrintI=1
PrintB=2
Bool=3
BoolNot=4
BoolEQ=5
BoolNE=6
Int=7
IntAdd=8
IntSub=9
IntMul=10
IntDiv=11
IntMod=12
IntLT=13
IntGT=14
IntLE=15
IntGE=16
IntEQ=17
IntNE=18
Float=19
FloatAdd=20
FloatSub=21
FloatMul=22
FloatDiv=23
FloatMod=24
FloatLT=25
FloatGT=26
FloatLE=27
FloatGE=28
FloatEQ=29
FloatNE=30
P=31
Pr=32
Pri=33
Prin=34
Print=35
PrintF=36
